### ISSUE TITLE
missing train_fold_sift_multi_gpu.py

### ISSUE THREAD

**Issue by chdjianfeng** [ShoupingShan/dfc2019_track4#1]
@ShoupingShan 
Hello. Thank you for your great job and opensource code. When I wanted to reproduce your results, I found that there was a lack of file "train_fold_sift_multi_gpu.py". Is that convenient for you to provide it? Thank you! Looking forward to your reply.

**Comment by ShoupingShan** [comment]
@yinianqingzhi 
Script [train_fold_sift_multi_gpu.py](https://github.com/ShoupingShan/dfc2019_track4/blob/master/dfc/train_fold_sift_multi_gpu.py) is now updated!

**Comment by chdjianfeng** [comment]
@ShoupingShan Thank you very much!
